const siteContent = [
  {
    heading: "Get Your VIN CHECK Today!",
    paragraphs: [
      "Don't Risk Buying a Dodgy Car! Secure your investment today with a vin check report.",
    ],
    button: {
      link: "/",
      label: "Get Report",
    },
    a: [
      {
        link: "/",
        label: "Where can I find the VIN",
      },
      {
        link: "/",
        label: "View Sample Report",
      },
    ],
  },
  {
    heading: "Australia's Fast and Comprehensive VIN Check Report",
    paragraphs: [
      "Run a VIN Number Check and get the history of the vehicle in seconds! Check the rego expiration date, state of registration, stolen vehicle status, financial interests, and more with a quick VIN Check report delivered right to your phone and email.",
    ],
  },
  {
    heading: "Motor Vehicle Search & Why It Matters",
    paragraphs: [
      "Ready to buy a used car but worried about the reports on stolen vehicles and an increase in sales of lemons? Want to get a car history report before the car you like is sold? Then you should run a motor vehicle search online that gives you fast results at a cheaper price.",
      "If you are planning to buy a second-hand vehicle, then run a VIN check first. With a comprehensive vehicle background report, you can avoid buying a lemon, losing the car to repossession or paying out more for repairs than expected. Plus, you get your results fast, so you can catch that car you've had your eye on before someone else does.",
      "This and more you can do with a motor vehicle search. Also, it is a simple process. Just use the VIN number and the easy-to-use online search platform.",
    ],
    a: [
      {
        link: "/",
        label: "Read More ",
      },
    ],
  },
  {
    heading: "What is Australian VIN Check?",
    paragraphs: [
      "A VIN check is a search of the government PPSR register for the car history details. You use the VIN - a 17-digit alphanumeric number - to search the Personal Property Securities Register (PPSR). With our VIN Check report , you get a comprehensive report AND an official PPSR certificate generated by the Australian government register.",
    ],
  },
  {
    heading: "Choosing the Best VIN Check Online Service in Australia",
    paragraphs: [
      "We want to help you get the best out of your used car buying experience. Let us help you make the best decision. Avoid a lemon. Get the facts. Request an official government PPSR certificate with your VIN Check report.",
      "What also sets us apart is that you get more for less. Vin Check Report gives a more detailed VIN number check report for a lower fee.",
      "Plus, it's fast. Don't wait until it's too late and lose out on that car you want. Get a VIN report in seconds so you can make a decision faster.",
    ],
  },
  {
    heading: "Reveal the History of Your Next Car With Us!",
    paragraphs: ["Before it's late"],
    a: [
      {
        link: "/",
        label: "Buy Now!",
      },
    ],
  },
];

export default siteContent;
